name: Docker Build and Push
on:
  push:
    branches:
      - docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }}

      - name: Deploy the Image
        uses: azure/webapps-deploy@v2
        with:
          app-name: "dotnet-practice-image"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: "${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }}"
